In [1]:

from platform import python_version

print(python_version())

3.7.4


In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib as plt
%matplotlib inline

In [2]:
raw_data= pd.read_csv('final_hotel_dataset.csv')

In [3]:
raw_data.drop(['Unnamed: 0'],axis=1,inplace=True)



In [4]:
raw_data.drop(raw_data[raw_data['children'].isnull()].index,axis=0,inplace=True)

In [5]:
input_data=raw_data.iloc[:,:-1]

In [6]:
input_data


hotel  lead_time  stays_in_weekend_nights  stays_in_week_nights  \
0           1        342                        0                     0   
1           1          7                        0                     1   
2           1         13                        0                     1   
3           1         14                        0                     2   
4           1         14                        0                     2   
...       ...        ...                      ...                   ...   
103834      0         23                        2                     5   
103835      0        102                        2                     5   
103836      0         34                        2                     5   
103837      0        109                        2                     5   
103838      0        205                        2                     7   

        adults  children  babies  is_repeated_guest  previous_cancellations  \
0            2       0.0       0                  0                       0   
1            1       0.0       0                  0                       0   
2            1       0.0       0                  0                       0   
3            2       0.0       0                  0                       0   
4            2       0.0       0                  0                       0   
...        ...       ...     ...                ...                     ...   
103834       2       0.0       0                  0                       0   
103835       3       0.0       0                  0                       0   
103836       2       0.0       0                  0                       0   
103837       2       0.0       0                  0                       0   
103838       2       0.0       0                  0                       0   

        previous_bookings_not_canceled  ...  Undefined  Undefined.1  \
0                                    0  ...          0            0   
1                                    0  ...          0            0   
2                                    0  ...          0            0   
3                                    0  ...          0            0   
4                                    0  ...          0            0   
...                                ...  ...        ...          ...   
103834                               0  ...          0            0   
103835                               0  ...          0            0   
103836                               0  ...          0            0   
103837                               0  ...          0            0   
103838                               0  ...          0            0   

        Complementary  Corporate  Direct  Groups  Offline TA/TO  Online TA  \
0                   0          0       1       0              0          0   
1                   0          0       1       0              0          0   
2                   0          1       0       0              0          0   
3                   0          0       0       0              0          1   
4                   0          0       0       0              0          1   
...               ...        ...     ...     ...            ...        ...   
103834              0          0       0       0              1          0   
103835              0          0       0       0              0          1   
103836              0          0       0       0              0          1   
103837              0          0       0       0              0          1   
103838              0          0       0       0              0          1   

        Undefined.2  Undefined.3  
0                 0            0  
1                 0            0  
2                 0            0  
3                 0            0  
4                 0            0  
...             ...          ...  
103834            0            0  
103835            0            0  
103836            0            0  
103837            

In [7]:
input_data.drop(['Online TA','children','stays_in_weekend_nights','PRT','ITA','BRA','adults','deposit_type','Undefined','Undefined.1','Undefined.2','Undefined.3'],axis=1,inplace=True)

In [8]:
target_data=raw_data.iloc[:,-1]

In [9]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

def calc_vif(X):

    # Calculating VIF
    vif = pd.DataFrame()
    vif["variables"] = X.columns
    vif["VIF"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]

    return(vif)

In [10]:
calc_vif(input_data)

variables       VIF
0                            hotel  2.077304
1                        lead_time  2.956299
2             stays_in_week_nights  4.261202
3                           babies  1.019306
4                is_repeated_guest  2.789552
5           previous_cancellations  1.294534
6   previous_bookings_not_canceled  2.897031
7             days_in_waiting_list  1.122765
8                              adr  6.591751
9      required_car_parking_spaces  1.180268
10       total_of_special_requests  2.124809
11                           Month  5.129371
12                     day_of_week  3.246909
13                   room_matching  6.868626
14                             BEL  1.066819
15                             CHE  1.053038
16                              CN  1.038232
17                             DEU  1.192153
18                             ESP  1.221447
19                             FRA  1.264723
20                             GBR  1.353916
21                             IRL  1.129557
22                             NLD  1.059742
23                             SWE  1.028644
24                             USA  1.064067
25                              FB  1.045311
26                              HB  1.302548
27                              SC  1.233303
28                   Complementary  1.070767
29                       Corporate  1.334937
30                          Direct  1.303212
31                          Groups  1.868531
32                   Offline TA/TO  1.799063

# Standardized the data

In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
scaler= StandardScaler()

In [13]:
scaler.fit(input_data)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [14]:
scaled_inputs=scaler.transform(input_data)

# Train_test_split

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
train_test_split(scaled_inputs,target_data)

[array([[-0.7181888 ,  1.79265469, -0.24454671, ..., -0.34448591,
         -0.44892066,  1.93767064],
        [-0.7181888 , -0.97428112, -0.88522158, ..., -0.34448591,
          2.22756513, -0.51608358],
        [-0.7181888 , -0.92265918,  1.67747789, ..., -0.34448591,
         -0.44892066, -0.51608358],
        ...,
        [ 1.39239152, -0.79876653, -0.24454671, ..., -0.34448591,
         -0.44892066, -0.51608358],
        [-0.7181888 ,  1.87524979, -0.24454671, ..., -0.34448591,
          2.22756513, -0.51608358],
        [-0.7181888 , -0.4993593 ,  0.39612816, ..., -0.34448591,
         -0.44892066, -0.51608358]]),
 array([[-0.7181888 ,  0.33691607, -0.24454671, ..., -0.34448591,
         -0.44892066, -0.51608358],
        [-0.7181888 , -0.67487388, -0.88522158, ..., -0.34448591,
         -0.44892066, -0.51608358],
        [-0.7181888 ,  2.12303508, -0.24454671, ..., -0.34448591,
         -0.44892066,  1.93767064],
        ...,
        [-0.7181888 , -0.80909092, -0.24454671, ..., -

In [17]:
x_train,x_test,Y_train,Y_test=train_test_split(scaled_inputs,target_data,test_size=0.2)

In [18]:
from sklearn.linear_model import LogisticRegression

In [19]:
reg= LogisticRegression()

In [20]:
reg.fit(x_train,Y_train)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [21]:
reg.score(x_train,Y_train)

0.7975273270091973

In [22]:
model_predict=reg.predict(x_train)

In [23]:
np.sum(model_predict==Y_train)

66249

In [24]:
reg.intercept_

array([-1.19964649])

In [25]:
reg.coef_

array([[-0.02455159,  0.59089031,  0.0763279 , -0.02143712, -0.19346079,
         1.05847558, -0.51602586,  0.02099767,  0.30081293, -2.05132967,
        -0.66701276, -0.098698  ,  0.06714745,  0.7269491 , -0.27616498,
        -0.2203383 , -0.18696722, -0.54306299, -0.2953529 , -0.53569734,
        -0.59620985, -0.29942476, -0.26700204, -0.19169111, -0.21401945,
         0.04784417, -0.14280872,  0.05201227, -0.0666169 , -0.28687204,
        -0.48655803, -0.25016601, -0.47898321]])

In [26]:
feature_name=input_data.columns.values

In [27]:
summery_table=pd.DataFrame(columns=['feature_name'],data=feature_name)

In [28]:
from sklearn.feature_selection import f_regression

In [29]:
f_regression(x_train,Y_train)

(array([1.47586532e+03, 8.28466294e+03, 4.65212752e+01, 6.60519733e+01,
        6.62210773e+02, 7.61327315e+03, 1.15268552e+03, 1.09133217e+03,
        2.58769877e+02, 3.42650034e+03, 6.10343116e+03, 2.33835122e+01,
        4.82134806e+01, 5.64534514e+03, 2.30533707e+02, 1.06632125e+02,
        1.18189536e+02, 9.83930417e+02, 4.36421059e+02, 1.39138745e+03,
        1.17308524e+03, 1.68138988e+02, 2.53437831e+02, 8.18197158e+01,
        1.22070565e+02, 1.65530936e+02, 9.06065761e+00, 1.36098814e+01,
        1.50760462e+02, 5.58801698e+02, 2.12211233e+03, 4.71358850e+03,
        6.35714297e+00]),
 array([4.51477187e-320, 0.00000000e+000, 9.12464290e-012, 4.45165415e-016,
        1.84257116e-145, 0.00000000e+000, 6.19456518e-251, 8.88918964e-238,
        3.89648528e-058, 0.00000000e+000, 0.00000000e+000, 1.32948115e-006,
        3.85044664e-012, 0.00000000e+000, 5.35659087e-052, 5.54969967e-025,
        1.64462736e-027, 1.01227599e-214, 1.15501334e-096, 5.01306376e-302,
        2.62830195

In [30]:
summery_table['coefficient']=np.transpose(reg.coef_)

In [31]:
p_values=f_regression(x_train,Y_train)[1].round(3)

In [32]:
summery_table['p_values']=p_values

In [33]:
summery_table

feature_name  coefficient  p_values
0                            hotel    -0.024552     0.000
1                        lead_time     0.590890     0.000
2             stays_in_week_nights     0.076328     0.000
3                           babies    -0.021437     0.000
4                is_repeated_guest    -0.193461     0.000
5           previous_cancellations     1.058476     0.000
6   previous_bookings_not_canceled    -0.516026     0.000
7             days_in_waiting_list     0.020998     0.000
8                              adr     0.300813     0.000
9      required_car_parking_spaces    -2.051330     0.000
10       total_of_special_requests    -0.667013     0.000
11                           Month    -0.098698     0.000
12                     day_of_week     0.067147     0.000
13                   room_matching     0.726949     0.000
14                             BEL    -0.276165     0.000
15                             CHE    -0.220338     0.000
16                              CN    -0.186967     0.000
17                             DEU    -0.543063     0.000
18                             ESP    -0.295353     0.000
19                             FRA    -0.535697     0.000
20                             GBR    -0.596210     0.000
21                             IRL    -0.299425     0.000
22                             NLD    -0.267002     0.000
23                             SWE    -0.191691     0.000
24                             USA    -0.214019     0.000
25                              FB     0.047844     0.000
26                              HB    -0.142809     0.003
27                              SC     0.052012     0.000
28                   Complementary    -0.066617     0.000
29                       Corporate    -0.286872     0.000
30                          Direct    -0.486558     0.000
31                          Groups    -0.250166     0.000
32                   Offline TA/TO    -0.478983     0.012

In [34]:
reg.score(x_test,Y_test)

0.7949631627100688

In [35]:
Y_pred=reg.predict(x_test)

In [36]:
from sklearn.metrics import classification_report,confusion_matrix,roc_auc_score

In [37]:
print(classification_report(Y_test,Y_pred))

              precision    recall  f1-score   support

           0       0.82      0.87      0.84     13002
           1       0.75      0.67      0.71      7765

    accuracy                           0.79     20767
   macro avg       0.78      0.77      0.78     20767
weighted avg       0.79      0.79      0.79     20767



In [38]:
print(confusion_matrix(Y_test,Y_pred))


[[11308  1694]
 [ 2564  5201]]


In [39]:
print(roc_auc_score(y_score=Y_pred, y_true = Y_test))

0.7697563691474283


# Decision Tree

In [40]:
from sklearn.tree import DecisionTreeClassifier

In [41]:
dtree = DecisionTreeClassifier()

In [42]:
dtree.fit(x_train,Y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [43]:
predictions = dtree.predict(x_test)

In [44]:
dtree.score(x_train,Y_train)

0.9937159917176289

In [45]:
dtree.score(x_test,Y_test)

0.8334376655270381

In [46]:
from sklearn.metrics import classification_report,confusion_matrix

In [47]:
print(classification_report(Y_test,predictions))

              precision    recall  f1-score   support

           0       0.87      0.86      0.87     13002
           1       0.77      0.78      0.78      7765

    accuracy                           0.83     20767
   macro avg       0.82      0.82      0.82     20767
weighted avg       0.83      0.83      0.83     20767



In [48]:
print(confusion_matrix(Y_test,predictions))

[[11228  1774]
 [ 1685  6080]]


In [49]:
print(roc_auc_score(y_score=predictions, y_true = Y_test))

0.8232800481534714


# Random Forest

In [50]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=200)
rfc.fit(x_train, Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=200,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [51]:
rfc_pred = rfc.predict(x_test)

In [52]:
rfc.score(x_train,Y_train)

0.9937159917176289

In [53]:
rfc.score(x_test,Y_test)

0.8749939808349786

In [54]:
print(confusion_matrix(Y_test,rfc_pred))

[[12064   938]
 [ 1658  6107]]


In [55]:
print(classification_report(Y_test,rfc_pred))

              precision    recall  f1-score   support

           0       0.88      0.93      0.90     13002
           1       0.87      0.79      0.82      7765

    accuracy                           0.87     20767
   macro avg       0.87      0.86      0.86     20767
weighted avg       0.87      0.87      0.87     20767



In [56]:
print(roc_auc_score(y_score=rfc_pred, y_true = Y_test))

0.857167518831369


#  KNN

In [57]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
error_rate = []

for i in range(20,40):
    
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(x_train,Y_train)
    pred_i = knn.predict(x_test)
    error_rate.append(np.mean(pred_i != Y_test))

In [ ]:
plt.figure(figsize=(10,6))
plt.plot(range(1,40),error_rate,color='blue', linestyle='dashed', marker='o',
         markerfacecolor='red', markersize=10)
plt.title('Error Rate vs. K Value')
plt.xlabel('K')
plt.ylabel('Error Rate')

# Support Vector Machine 

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'sigmoid', random_state = 0)
classifier.fit(x_train, Y_train)

In [ ]:
y_pred1 = classifier.predict(x_test)

In [ ]:
print(confusion_matrix(Y_test,y_pred1))

In [ ]:
print(classification_report(Y_test,y_pred1))

In [ ]:
print(roc_auc_score(y_score=y_pred1, y_true = Y_test))